# This is the parameter configuration file for PaddleSpeech Serving.

##################################################################
#                     SERVER SETTING                             #
##################################################################
host: '0.0.0.0'
port: 8090

