###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
# currently, we only support fbank
feature:
  n_mels: 80
  window_size: 400     #25ms, sample rate 16000, 25 * 16000 / 1000 = 400 
  hop_length: 160     #10ms, sample rate 16000, 10 * 16000 / 1000 = 160


###########################################################
#                       MODEL SETTING                     #
###########################################################
# currently, we only support ecapa-tdnn in the ecapa_tdnn.yaml
# if we want use another model, please choose another configuration yaml file
model:
  input_size: 80
  ##"channels": [1024, 1024, 1024, 1024, 3072],
  # "channels": [512, 512, 512, 512, 1536],
  channels: [512, 512, 512, 512, 1536]
  kernel_sizes: [5, 3, 3, 3, 1]
  dilations: [1, 2, 3, 4, 1]
  attention_channels: 128
  lin_neurons: 192

###########################################
#                Training                 #
###########################################
seed: 0
epochs: 10
batch_size: 32
num_workers: 2
save_freq: 10
log_freq: 10
learning_rate: 1e-8
