###########################################
#                Data                 #
###########################################
batch_size: 32
num_workers: 2
num_speakers: 7205 # 1211 vox1, 5994 vox2, 7205 vox1+2, test speakers: 41
shuffle: True
random_chunk: True

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
# currently, we only support fbank
feature:
  n_mels: 80
  window_size: 400     #25ms, sample rate 16000, 25 * 16000 / 1000 = 400 
  hop_length: 160     #10ms, sample rate 16000, 10 * 16000 / 1000 = 160

###########################################################
#                       MODEL SETTING                     #
###########################################################
# currently, we only support ecapa-tdnn in the ecapa_tdnn.yaml
# if we want use another model, please choose another configuration yaml file
model:
  input_size: 80
  # "channels": [512, 512, 512, 512, 1536],
  channels: [1024, 1024, 1024, 1024, 3072]
  kernel_sizes: [5, 3, 3, 3, 1]
  dilations: [1, 2, 3, 4, 1]
  attention_channels: 128
  lin_neurons: 192

###########################################
#                Training                 #
###########################################
seed: 1986 # according from speechbrain configuration
epochs: 10
save_freq: 10
log_interval: 10
learning_rate: 1e-8

